import Head from "next/head";
import Image from "next/image";

export default function non_veg() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <header className="text-amber-100 body-font bg-black">
          <div className="relative">
            <Image
              src="/tikka.jpg"
              className="absolute inset-0 object-cover w-full h-full blur-sm"
              alt="blob"
              width={500}
              height={500}
            />
            <div className="relative bg-stone-900 bg-opacity-70">
              <div className="px-4 py-16 mx-auto sm:max-w-xl md:max-w-full lg:max-w-screen-xl md:px-24 lg:px-8 lg:py-20">
                <h2 className="text-4xl font-bold text-amber-500 lg:text-4xl">
                  Recipe Book
                </h2>
                <p className="mt-4 text-sm text-amber-200 lg:text-base">
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                  Blanditiis commodi cum cupiditate ducimus, fugit harum id
                  necessitatibus odio quam quasi, quibusdam rem tempora
                  voluptates.
                </p>
                <br />
              </div>
            </div>
          </div>
          <hr
            style={{
              color: "#3f2e2cc0",
              backgroundColor: "#D4645C",
              height: 6,
              borderColor: "#3f2e2cc0",
            }}
          />
        </header>

        <section className="bg-amber-100">
          <div className="container px-5 py-24 mx-auto">
            <div className="flex flex-wrap -m-4">
              <div className="p-4 md:w-1/3">
                <div className="h-full border-2 border-gray-200 border-opacity-60 rounded-lg overflow-hidden bg-gradient-to-r from-[#520301] to-[#ac4814] shadow-lg">
                  <Image
                    className="lg:h-48 md:h-36 w-full object-cover object-center"
                    src="/prawn_1.png"
                    alt="blob"
                    width={500}
                    height={500}
                  ></Image>
                  <div className="p-6">
                    <a
                      className="bg-gradient-to-r from-stone-900 via-stone-800 to-orange-900 shadow-lg inline-flex items-center rounded-lg px-8 py-3 text-orange-300 hover:bg-stone-800 hover:text-white focus:outline-none focus:ring active:bg-white/90"
                      href="#"
                    >
                      <span className="text-lg font-medium">
                        Prawn Mushroom with Cashew Receipe
                      </span>
                      <svg
                        className="ml-3 h-5 w-5"
                        xmlns="http://www.w3.org/2000/svg"
                        fill="none"
                        viewBox="0 0 24 24"
                        stroke="currentColor"
                      >
                        <path
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          strokeWidth="2"
                          d="M17 8l4 4m0 0l-4 4m4-4H3"
                        />
                      </svg>
                    </a>
                    <br></br>
                    <br></br>
                    <h1 className="title-font text-lg font-medium text-white mb-3 ">
                      Ingrediants
                    </h1>
                    <p className="leading-relaxed mb-3 text-orange-100">
                      <span className="text-orange-300 font-bold">1.</span>
                      Prawn<br></br>
                      <span className="text-orange-300 font-bold">2.</span>
                      Button Mushroom<br></br>
                      <span className="text-orange-300 font-bold">3.</span>
                      Cashew paste<br></br>
                      <span className="text-orange-300 font-bold">4.</span>
                      Tomato, chilli, onions, ginger paste<br></br>
                      <span className="text-orange-300 font-bold">5.</span>
                      Turmeric powder, salt, red chilli powder.<br></br>
                    </p>
                  </div>
                </div>
              </div>
              {/* <div className="p-4 md:w-1/3">
<div className="h-full border-2 border-gray-200 border-opacity-60 rounded-lg overflow-hidden bg-gradient-to-r from-[#520301] to-[#ac4814] shadow-lg">
<Image
className="lg:h-48 md:h-36 w-full object-cover object-center"
src="/tikka.jpg"
alt="blob"
width={500}
height={500}
></Image>
<div className="p-6">
<a
className="bg-gradient-to-r from-stone-900 via-stone-800 to-orange-900 shadow-lg inline-flex items-center rounded-lg px-8 py-3 text-orange-300 hover:bg-stone-800 hover:text-white focus:outline-none focus:ring active:bg-white/90"
href="#"
>
<span className="text-lg font-medium">
Chicken Tikka Masala Receipe
</span>
<svg
className="ml-3 h-5 w-5"
xmlns="http://www.w3.org/2000/svg"
fill="none"
viewBox="0 0 24 24"
stroke="currentColor"
>
<path
strokeLinecap="round"
strokeLinejoin="round"
strokeWidth="2"
d="M17 8l4 4m0 0l-4 4m4-4H3"
/>
</svg>
</a>
<br></br>
<br></br>
<h1 className="title-font text-lg font-medium text-white mb-3 ">
Ingrediants
</h1>
<p className="leading-relaxed mb-3 text-orange-100">
<span className="text-orange-300 font-bold">1.</span> 100g
Shemin’s Indian Curry Paste<br></br>
<span className="text-orange-300 font-bold">2.</span> 2
tsp Shemin’s Garam Masala<br></br>
<span className="text-orange-300 font-bold">3.</span>
375ml full fat yoghurt<br></br>
<span className="text-orange-300 font-bold">4.</span> 1
tsp salt (optional)<br></br>
<span className="text-orange-300 font-bold">5.</span> 750g
skinless, boneless chicken breasts, halved lengthwise into
strips<br></br>
<span className="text-orange-300 font-bold">6.</span> 2
tbsp oil<br></br>
<span className="text-orange-300 font-bold">7.</span> 1
small onion, thinly sliced<br></br>
<span className="text-orange-300 font-bold">8.</span> 1
tbsp tomato paste<br></br>
<span className="text-orange-300 font-bold">9.</span> 6
cardamom pods, crushed (optional)<br></br>
<span className="text-orange-300 font-bold">10.</span> 1 x
400g can chopped tomatoes<br></br>
<span className="text-orange-300 font-bold">11.</span> 2
small green chillies, split (optional)<br></br>
<span className="text-orange-300 font-bold">12.</span>
100ml whipping cream<br></br>
<span className="text-orange-300 font-bold">13.</span> 3/4
cup chopped fresh coriander plus sprigs for garnish
<br></br>
<span className="text-orange-300 font-bold">14.</span>
Juice of 1 lime or lemon<br></br>
<span className="text-orange-300 font-bold">15.</span>
Steamed basmati rice (for serving)<br></br>
</p>
</div>
</div>
</div> */}
              {/* <div className="p-4 md:w-1/3">
<div className="h-full border-2 border-gray-200 border-opacity-60 rounded-lg overflow-hidden bg-gradient-to-r from-[#520301] to-[#ac4814] shadow-lg">
<Image
className="lg:h-48 md:h-36 w-full object-cover object-center"
src="/prawn_1.png"
alt="blob"
width={500}
height={500}
></Image>
<div className="p-6">
<a
className="bg-gradient-to-r from-stone-900 via-stone-800 to-orange-900 shadow-lg inline-flex items-center rounded-lg px-8 py-3 text-orange-300 hover:bg-stone-800 hover:text-white focus:outline-none focus:ring active:bg-white/90"
href="#"
>
<span className="text-lg font-medium">
Prawn Mushroom with Cashew Receipe
</span>
<svg
className="ml-3 h-5 w-5"
xmlns="http://www.w3.org/2000/svg"
fill="none"
viewBox="0 0 24 24"
stroke="currentColor"
>
<path
strokeLinecap="round"
strokeLinejoin="round"
strokeWidth="2"
d="M17 8l4 4m0 0l-4 4m4-4H3"
/>
</svg>
</a>
<br></br>
<br></br>
<h1 className="title-font text-lg font-medium text-white mb-3 ">
Ingrediants
</h1>
<p className="leading-relaxed mb-3 text-orange-100">
<span className="text-orange-300 font-bold">1.</span>
Prawn<br></br>
<span className="text-orange-300 font-bold">2.</span>
Button Mushroom<br></br>
<span className="text-orange-300 font-bold">3.</span>
Cashew paste<br></br>
<span className="text-orange-300 font-bold">4.</span>
Tomato, chilli, onions, ginger paste<br></br>
<span className="text-orange-300 font-bold">5.</span>
Turmeric powder, salt, red chilli powder.<br></br>
</p>
</div>
</div>
</div> */}
            </div>
          </div>{" "}
          <hr
            style={{
              color: "#3f2e2cc0",
              backgroundColor: "#D4645C",
              height: 6,
              borderColor: "#3f2e2cc0",
            }}
          />
        </section>

        <footer className="bg-neutral-900 text-amber-400 body-font">
          <div className="container px-5 py-8 mx-auto flex items-center sm:flex-row flex-col">
            <a className="flex title-font font-medium items-center md:justify-start justify-center text-amber-500">
              <span className="ml-3 text-xl hover:text-amber-600">
                <b>❝ Coded by ⒸKryKenz ❞</b>
              </span>
            </a>
            <p className="text-sm text-white sm:ml-4 sm:pl-4 sm:border-l-2 sm:border-amber-800 sm:py-2 sm:mt-0 mt-4">
              <b>Since 2021 and Forever</b>
              <a
                href="https://github.com/KryKenz/Vlkyre/blob/krytek/LICENSE"
                className="text-amber-500 ml-1 hover:text-amber-200"
                target="_blank"
                rel="noopener noreferrer"
              >
                <i>Licensed Under Mozilla Public License 2.0</i>
              </a>
            </p>
            <span className="inline-flex sm:ml-auto sm:mt-0 mt-4 justify-center sm:justify-start"></span>
            <a
              className="inline-flex items-center rounded-full bg-stone-900 px-8 py-3 text-amber-600 hover:bg-stone-800 hover:text-white focus:outline-none focus:ring active:bg-white/90"
              href="#"
            >
              <span className="text-sm font-medium"> Back To Top </span>
              <svg
                className="ml-3 h-5 w-5"
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth="2"
                  d="M17 8l4 4m0 0l-4 4m4-4H3"
                />
              </svg>
            </a>
          </div>
        </footer>
      </main>
    </>
  );
}
